### ISSUE TITLE
Sketch 'Tints' not recognised

### ISSUE THREAD

**Issue by Atim33** [romannurik/Sketch-Contrast#14]
Hi Roman great plugin (always in my toolbox), would be great if you could support Sketchs "Tint" capability as we are increasingly having more fonts with tints applied throughout our projects, these tend to fail the contrast check as the underling font colour is used for the check and not the visible applied tint.

Sketch tints: https://www.sketch.com/blog/2020/03/23/tints-a-new-components-menu-and-more-whats-new-in-sketch/

thanks

**Comment by romannurik** [comment]
Ah yes, good catch. Don't know when I'll have time to do this, but definitely needs to be done
