### ISSUE TITLE
Not working anymore - Stop after duplicationg an artboard

### ISSUE THREAD

**Issue by rodnem** [romannurik/Sketch-Contrast#22]
Hello

I'm under Sketch Version 76.1 (130273)
with your v0.1.8 plugin

It seems that the plugin is no more able to analyse and flatten the result

Thank you

**Comment by rodnem** [comment]
https://www.loom.com/share/879e94cd182d48f4b926596302992a2b

**Comment by romannurik** [comment]
Looks like there's a bug with the latest version of Sketch... will look into it! Thank you for filing!

**Comment by romannurik** [comment]
Fixed in v0.1.9!
