### ISSUE TITLE
.sketchplugin is missing

### ISSUE THREAD

**Issue by fabianmercey** [romannurik/Sketch-Contrast#5]
Upon downloading the file package, the `.sketchplugin` is missing.

**Comment by romannurik** [comment]
Hi there, I'm able to see the .sketchplugin just fine from this link:

https://github.com/romannurik/Sketch-Contrast/releases/download/v0.1.5/Contrast.sketchplugin.zip

**Comment by fabianmercey** [comment]
<img width="337" alt="schermafbeelding 2019-02-19 om 15 17 29" src="https://user-images.githubusercontent.com/11908417/53021525-b088cd80-3459-11e9-98c8-d496ad083322.png">
This is all I see after downloading the zip file.

**Comment by romannurik** [comment]
It looks like you're downloading the source file. Go here:

https://github.com/romannurik/Sketch-Contrast/releases

And click the link that says "To install: download this...."
