### ISSUE TITLE
Icon contrast

### ISSUE THREAD

**Issue by alexandrucene** [romannurik/Sketch-Contrast#7]
Hey Roman, I find your plugin of the best contrast extension for Sketch.

Wondering if it could be enhanced to display also contrast values for icons as well.

**Comment by romannurik** [comment]
The tricky thing is icons take many forms — shape layers, symbols, etc. How do you use icons? Symbols?

**Comment by alexandrucene** [comment]
Most of the times it's symbols and I would be interested in the contract between the main color and the background.

In the early design iterations, I'm just drag&drop-ing Material Design icons as SVG groups. For some of them, I'm changing the shape's background from black to a shade of grey or to a color.

**Comment by romannurik** [comment]
Gotcha. That does make it quite difficult to distinguish icons from other
shapes :/

**Comment by alexandrucene** [comment]
You are right, probably not all use case can be covered easily.  I would appreciate the most common one, that I guess it's symbols.

**Comment by romannurik** [comment]
Closing as infeasible given the variety of ways icons are handled + colored today in Sketch
